#!/bin/bash
interval=0.1
sleep $interval
xdotool keydown Shift
sleep $interval
xdotool keydown s
sleep $interval
xdotool mousedown 3
sleep $interval

while [ `./is_to_continue` -eq 1 ]
do
echo "loop"
sleep 1
done

echo "over"
xdotool keyup Shift
sleep $interval
xdotool keyup s
sleep $interval
xdotool mouseup 3

