#!/bin/bash

interval=0.1
xdotool keydown w
sleep 0.05
xdotool key ctrl
while [ `./is_to_continue` -eq 1 ]
	do

	sleep $interval
	xdotool keydown space
	sleep $interval
	xdotool keyup space

	done


sleep $interval
xdotool keyup w
