#!/bin/bash
#usage: move mouse to potato or others and use this
#no need to kill


##default config for 1366x768
base_x=536
base_y=536

##default config for 1920x1080
#base_x=816
#base_y=662

if [ "$1" != "" ]
then
    base_x="$1"
fi

if [ "$2" != "" ]
then
    base_y="$2"
fi



short_interval=0.03
long_interval=0.08

sleep $short_interval
xdotool click 1
xdotool click 1
sleep $short_interval

#dick_left_x=598
#dick_left_y=346

#dick_right_x=765
#dick_right_y=346

dick_left_x=$(( $base_x + 62 ))
dick_left_y=$(( $base_y + -190 ))

dick_right_x=$(( $base_x + 229 ))
dick_right_y=$(( $base_y + -190 ))

#get start position
start_position_x=`xdotool getmouselocation | grep -Po '\d+' | head -n 1`
start_position_y=`xdotool getmouselocation | grep -Po '\d+' | head -n 2 | tail -n 1`
sleep $short_interval

echo $start_position_x
echo $start_position_y

#move to dick left
xdotool mousemove $dick_left_x $dick_left_y
sleep $short_interval
xdotool click 1

#while (true)
for i in {1..4}
	do
	 
#take emerald
	sleep 0.03
	xdotool mousemove $dick_right_x $dick_right_y
	sleep $short_interval
	xdotool keydown "shift"
	sleep $long_interval
	xdotool click 1
	sleep $long_interval
	xdotool keyup "shift"

#move to left and click for 3 times
	sleep $short_interval
	xdotool mousemove $dick_left_x $dick_left_y
	sleep $short_interval
	xdotool click 1
	xdotool click 1
	xdotool click 1

	done
#take emerald
xdotool mousemove $dick_right_x $dick_right_y
sleep $short_interval
xdotool keydown "shift"
sleep $long_interval
xdotool click 1
sleep $long_interval
xdotool keyup "shift"
#move to left
sleep $short_interval
xdotool mousemove $dick_left_x $dick_left_y
sleep $short_interval

#move the item to start position
xdotool click 1
sleep $short_interval
xdotool mousemove $start_position_x $start_position_y
sleep $short_interval
xdotool click 1
sleep $long_interval
xdotool key Escape
